default_install_hook_types:
- pre-commit
- post-checkout


repos:
- repo: local
  hooks:
  - id: tuist
    name: tuist
    entry: tuist generate --no-open
    language: system
    always_run: true
    stages: [post-checkout]
